//用户管理
//游客部分
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const KEEP_ALIVE = "KEEP_ALIVE";
export const REGISTER = "REGISTER";
export const QUERY_RESOURCE = "QUERY_RESOURCE";
export const TEACHERRES = "TEACHERRES";
export const HANDLE_TEACHERRES_SUCCESS = "HANDLE_TEACHERRES_SUCCESS";
//学生部分
export const QUERY_HOMEWORK = "QUERY_HOMEWORK";
export const QUERY_HOMEWORK_OK = "QUERY_HOMEWORK_OK";
//学生添加课程
//资源管理
export const CHANGE_TYPE = "CHANGE_TYPE";
export const FETCH_STUDY_RESOURCE = "FETCH_STUDY_RESOURCE";
export const FETCH_STUDY_RES_SUCCESS = "FETCH_STUDY_RES_SUCCESS";
export const FETCH_SOFTWARE_RES_SUCCESS = "FETCH_SOFTWARE_RES_SUCCESS";
export const FETCH_SOFTWARE_RESOURCE = "FETCH_SOFTWARE_RESOURCE";
//上传
export const FETCH_UPLOAD_RES = "FETCH_UPLOAD_RES";
export const FETCH_UPLOAD_SUCCESS = "FETCH_UPLOAD_SUCCESS";
export const FETCH_UPLOAD_DATA_SUCCESS = "FETCH_UPLOAD_DATA_SUCCESS";
export const FETCH_UPLOAD_SOFTWARE_SUCCESS = "FETCH_UPLOAD_SOFTWARE_SUCCESS";
//获取老师资源
export const FETCH_TEACHER_DATA = "FETCH_TEACHER_DATA";
export const FETCH_TEACHER_DATA_SUCCESS = "FETCH_TEACHER_DATA_SUCCESS";
export const FETCH_TEACHER_SOFTWARE = "FETCH_TEACHER_SOFTWARE";
export const FETCH_TEACHER_SOFTWARE_SUCCESS = "FETCH_TEACHER_SOFTWARE_SUCCESS";
//老师查询学生信息
export const FETCH_STUDENT_MESSAGE = "FETCH_STUDENT_MESSAGE";
export const FETCH_STUDENT_MESSAGE_SUCCESS = "FETCH_STUDENT_MESSAGE_SUCCESS";
//老师批准注册用户
export const REGISTERED = "registered";
export const registered_SUCCESS = "registered_SUCCESS";
//老师查询待批准的学生
export const FETCH_QUERY_REGISTER = "FETCH_QUERY_REGISTER";
export const FETCH_QUERY_REGISTER_SUCCESS = "FETCH_QUERY_REGISTER_SUCCESS";
//删除学习资源
export const DELETE_DATA = "DELETE_DATA";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
//删除软件资源
export const DELETE_SOFTWARE = "DELETE_SOFTWARE";
export const DELETE_SOFTWARE_SUCCESS = "DELETE_SOFTWARE_SUCCESS";
//搜索资源
export const FETCH_SEARCH_VALUE = "FETCH_SEARCH_VALUE";
export const FETCH_SEARCH_VALUE_SUCCESS = "FETCH_SEARCH_VALUE_SUCCESS";
export const FETCH_SEARCH_DATA_SUCCESS = "FETCH_SEARCH_DATA_SUCCESS";
export const FETCH_SEARCH_SOFTWARE_SUCCESS = "FETCH_SEARCH_SOFTWARE_SUCCESS";
//下载资源
export const MATERIAL_LOAD = "MATERIAL_LOAD";
export const FETCH_LOAD_RESOURCE_SUCCESS = "FETCH_LOAD_RESOURCE_SUCCESS";
//实验室公告
export const QUERY_ANNOUNCE = "QUERY_ANNOUNCE";
export const QUERY_ANNOUNCE_SUCCESS = "QUERY_ANNOUNCE_SUCCESS";
//超级管理员
export const FETCH_ADMINSIDE = "FETCH_ADMINSIDE";
export const FETCH_ADMINISTRATOR_DATA = "FETCH_ADMINISTRATOR_DATA";
export const FETCH_ADMINISTRATOR_DATA_SUCCESS = "FETCH_ADMINISTRATOR_DATA_SUCCESS";
export const FETCH_NEW_ADMIN = "FETCH_NEW_ADMIN";
export const FETCH_NEW_ADMIN_SUCCESS = "FETCH_NEW_ADMIN_SUCCESS";
export const FETCH_TEACHER_RES = "FETCH_TEACHER_RES";
export const FETCH_TEACHER_RES_SUCCESS = "FETCH_TEACHER_RES_SUCCESS";
export const ADD_NEW_TEACHER = "ADD_NEW_TEACHER";
export const ADD_NEW_TEACHER_SUCCESS = "ADD_NEW_TEACHER_SUCCESS";
//上机任务
export const QUERY_COURSE = "QUERY_COURSE";
export const QUERY_COURSE_RES_SUCCESS = "QUERY_COURSE_RES_SUCCESS";
export const QUERY_COURSE_TASK = "QUERY_COURSE_TASK";
export const QUERY_COURSE_TASK_SUCCESS = "QUERY_COURSE_TASK_SUCCESS";
//修改学生信息
export const PRESERVE = "PRESERVE";
export const PRESERVE_SUCCESS = "PRESERVE_SUCCESS";
//教师查询课程
export const FETCH_SEARCH_COURSE = "FETCH_SEARCH_COURSE";
export const FETCH_SEARCH_COURSE_SUCCESS = "FETCH_SEARCH_COURSE_SUCCESS";


//morning
//老师请求实验课程
export const TEACHER_QUERY_COURSE = "TEACHER_QUERY_COURSE";
export const TEACHER_QUERY_COURSE_SUCCESS = "TEACHER_QUERY_COURSE_SUCCESS";

//学生添加上机课程
export const STUDENT_ADD_COURSE = "STUDENT_ADD_COURSE";
export const STUDENT_ADD_COURSE_SUCCESS = "STUDENT_ADD_COURSE_SUCCESS";
//老师添加上机课程
export const TEACHER_ADD_COURSE = "TEACHER_ADD_COURSE";
export const TEACHER_ADD_COURSE_SUCCESS = "TEACHER_ADD_COURSE_SUCCESS";
//学生删除课程
export const STUDENT_DELETE_COURSE = "STUDENT_DELETE_COURSE";
export const STUDENT_DELETE_COURSE_SUCCESS = "STUDENT_DELETE_COURSE_SUCCESS";
//老师删除课程
export const TEACHER_DELETE_COURSE = "TEACHER_DELETE_COURSE";
export const TEACHER_DELETE_COURSE_SUCCESS = "TEACHER_DELETE_COURSE_SUCCESS";
//老师添加教学班课程备注
export const TEACHER_ADD_REMARK = "TEACHER_ADD_REMARK";
export const TEACHER_ADD_REMARK_SUCCESS = "TEACHER_ADD_REMARK_SUCCESS";

//老师学生查看自己的上机任务
export const QUERY_MY_COURSE = "QUERY_MY_COURSE";
export const QUERY_MY_COURSE_SUCCESS = "QUERY_MY_COURSE_SUCCESS";
//老师发布任务
export const TEACHER_RELEASE_TASKS = "TEACHER_RELEASE_TASKS";
export const TEACHER_RELEASE_TASKS_SUCCESS = "TEACHER_RELEASE_TASKS_SUCCESS";
export const TEACHER_RELEASE_TASKS_FAILED = "TEACHER_RELEASE_TASKS_FAILED";
//老师删除任务
export const TEACHER_DELETE_TASK = "TEACHER_DELETE_TASK";
export const TEACHER_DELETE_TASK_SUCCESS = "TEACHER_DELETE_TASK_SUCCESS";
//老师开启/关闭任务作业的上传
export const TEACHER_TOGGLE_TASK_UPLOAD = "TEACHER_TOGGLE_TASK_UPLOAD";
export const TEACHER_TOGGLE_TASK_UPLOAD_SUCCESS = "TEACHER_TOGGLE_TASK_UPLOAD_SUCCESS";
//老师查看学生作业
export const TEACHER_QUERY_SUBMIT = "TEACHER_QUERY_SUBMIT";
export const TEACHER_QUERY_SUBMIT_SUCCESS = "TEACHER_QUERY_SUBMIT_SUCCESS";
//老师查看未提交作业名单
export const TEACHER_QUERY_UNSUBMIT = "TEACHER_QUERY_UNSUBMIT";
export const TEACHER_QUERY_UNSUBMIT_SUCCESS = "TEACHER_QUERY_UNSUBMIT_SUCCESS";
//学生上传作业
export const STUDENT_UPLOAD_HOMEWORK = "STUDENT_UPLOAD_HOMEWORK";
export const STUDENT_UPLOAD_HOMEWORK_SUCCESS = "STUDENT_UPLOAD_HOMEWORK_SUCCESS";
export const STUDENT_UPLOAD_HOMEWORK_FAILED = "STUDENT_UPLOAD_HOMEWORK_FAILED";
//学生查看作业
export const STUDENT_QUERY_SUBMIT = "STUDENT_QUERY_SUBMIT";
export const STUDENT_QUERY_SUBMIT_SUCCESS = "STUDENT_QUERY_SUBMIT_SUCCESS";
//学生删除已提交作业
export const STUDENT_DELETE_HOMEWORK = "STUDENT_DELETE_HOMEWORK";
export const STUDENT_DELETE_HOMEWORK_SUCCESS = "STUDENT_DELETE_HOMEWORK_SUCCESS";
//老师修改任务
export const TEACHER_UPDATE_TASK = "TEACHER_UPDATE_TASK";
export const TEACHER_UPDATE_TASK_SUCCESS = "TEACHER_UPDATE_TASK_SUCCESS";
export const TEACHER_UPDATE_TASK_FAILED = "TEACHER_UPDATE_TASK_FAILED";
//老师批量下载作业
export const TEACHER_DOWNLOAD_SUBMIT = "TEACHER_DOWNLOAD_SUBMIT";
export const TEACHER_DOWNLOAD_SUBMIT_SUCCESS = "TEACHER_DOWNLOAD_SUBMIT_SUCCESS";
