//用户管理
//游客部分
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const QUERY_RESOURCE = "QUERY_RESOURCE";
//学生部分
export const QUERY_HOMEWORK = "QUERY_HOMEWORK";
export const QUERY_HOMEWORK_OK = "QUERY_HOMEWORK_OK";
//资源管理
export const FETCH_STUDY_RESOURCE = "FETCH_STUDY_RESOURCE";
export const FETCH_STUDY_RES_SUCCESS = "FETCH_STUDY_RES_SUCCESS";
export const FETCH_SOFTWARE_RES_SUCCESS = "FETCH_SOFTWARE_RES_SUCCESS";
export const FETCH_SOFTWARE_RESOURCE = "FETCH_SOFTWARE_RESOURCE";
//下载资源
export const MATERIAL_LOAD = "MATERIAL_LOAD";
export const FETCH_LOAD_RESOURCE_SUCCESS = "FETCH_LOAD_RESOURCE_SUCCESS";